// Re-export all API endpoints from organized folders
// This file maintains backward compatibility with existing imports

// Auth exports
export {
  forgotPasswordRequestOtp,
  forgotPasswordVerifyOtp,
  addUser,
  login,
  getCurrentUser,
  changePassword,
  logout,
  refreshTokens,
} from "./auth";

// Football exports
export {
  FOOTBALL_COMMENTARY_SSE_URL,
  getAllPlayers,
  getPlayerByName,
  getPlayerById,
  getFootballLeagueLeaders,
  getPlayersStats,
  getAllTeams,
  getTeamByName,
  getTeamById,
  getAllLeagues,
  getLeagueByName,
  getLeagueById,
  getStandingsByLeagueId,
  getStandingSeasonsByLeagueId,
  getFixturesByLeague,
  getFixtureDetails,
  getMatchInfo,
  postTeamHeadToHead,
  getMatchCommentary,
  getLiveFixtures,
  filterFavorites,
  addFavorite,
  getFavorites,
  deleteFavorite,
  clearTeamsCache,
  clearLeaguesCache,
  clearPlayersCache,
  clearAllCache,
  getTeamFixtures,
  getLeagueFixtures,
  getPlayerRatings,
  getFootballFixturesByDate,
  // Image/Logo endpoints
  getLeagueLogoById,
  getTeamLogoById,
  getPlayerImageById,
  // New Public / Management-backed endpoints (via managementApi)
  searchPublic,
  getPublicLeagues,
  getPublicLeagueById,
  getPublicLeagueTeams,
  getPublicLeaguePlayers,
  getPublicLeagueStandings,
  getPublicLeagueStatistics,
  getPublicLeagueFixtures,
  getPublicTeamById,
  getPublicPlayerById,
  getPublicPlayerStats,
  getPublicFixtures,
  getPublicFixtureById,
  getPublicFixtureLineups,
  // Types
  type FootballLeagueLeadersResponse,
  type FootballHeadToHeadItem,
  type FootballLiveFixture,
  type PublicLeagueSummary,
  type PublicLeagueDetail,
  type PublicTeam,
  type PublicTeamDetail,
  type PublicPlayerBrief,
  type PublicPlayerDetail,
  type PublicPlayerStats,
  type PublicStandingEntry,
  type PublicStandingsResponse,
  type PublicStatisticsResponse,
  type PublicFixture,
  type PublicSearchResponse,
} from "./football";

// Cricket exports
export {
  CRICKET_SCOREBOARD_SSE_URL,
  getCricketMatchSseUrl,
  getCricketHome,
  getCricketLive,
  getLiveCricketFixtures,
  getUpcomingCricketFixtures,
  getCricketSeriesList,
  getCricketSeriesById,
  getCricketFixturesBySeriesId,
  getCricketStandingsBySeriesId,
  getCricketMatchById,
  getCricketMatchCenter,
  getCricketVenue,
  getCricketInnings,
  getCricketManOfMatch,
  getCricketLineups,
  getCricketCommentary,
  getCricketWickets,
  getCricketLocalTeam,
  getCricketVisitorTeam,
  getCricketPlayerById,
} from "./cricket";

// Basketball exports
export {
  getBasketballLeagues,
  getBasketballLeagueById,
  getLiveBasketballMatches,
  getBasketballFixtures,
  searchBasketballFixturesByStatus,
  getBasketballFixturesByDate,
  getBasketballMatchDetail,
  getBasketballMatchPlayByPlay,
  getBasketballStandingsByLeagueId,
  getBasketballStandings,
  getBasketballTeams,
  getBasketballTeamDetail,
  getBasketballPlayers,
  getBasketballPlayerDetail,
  searchBasketballPlayers,
  compareBasketballTeams,
  compareBasketballPlayers,
  // Image/Logo endpoints
  getBasketballLeagueLogoById,
  getBasketballTeamLogoById,
  getBasketballPlayerImageById,
} from "./basketball";

// Tennis exports
export {
  getTennisLiveMatches,
  getTennisMatchesByDayOffset,
  getTennisLeagues,
} from "./tennis";

// Management API exports (direct import path: @/lib/api/management)
export {
  searchPublic as searchPublicManagement,
  getPublicLeagues as getManagementLeagues,
  getPublicLeagueById as getManagementLeagueById,
  getPublicLeagueTeams as getManagementLeagueTeams,
  getPublicLeaguePlayers as getManagementLeaguePlayers,
  getPublicLeagueStandings as getManagementLeagueStandings,
  getPublicLeagueStatistics as getManagementLeagueStatistics,
  getPublicLeagueFixtures as getManagementLeagueFixtures,
  getPublicTeamById as getManagementTeamById,
  getPublicPlayerById as getManagementPlayerById,
  getPublicPlayerStats as getManagementPlayerStats,
  getPublicFixtures as getManagementFixtures,
  getPublicFixtureById as getManagementFixtureById,
  getPublicFixtureLineups as getManagementFixtureLineups,
  type PublicLeagueSummary as ManagementLeagueSummary,
  type PublicLeagueDetail as ManagementLeagueDetail,
  type PublicTeam as ManagementTeam,
  type PublicPlayerBrief as ManagementPlayerBrief,
  type PublicPlayerStats as ManagementPlayerStats,
  type PublicFixture as ManagementFixture,
  type PublicSearchResponse as ManagementSearchResponse,
} from "./management";
